import os
import uuid
import re
from github import Github
from swarm.state import SwarmState

def github_action_agent(state: SwarmState) -> SwarmState:
    """Agent 6: Uses PyGithub to create a branch, apply the patch, and open a Pull Request."""
    state["current_agent"] = "GitHub Action Agent"
    
    token = os.environ.get("GITHUB_TOKEN")
    github_mode = os.environ.get("GITHUB_MODE", "SAFE").upper()
    repo_url = state.get("repo_url", "")
    files_modified = state.get("files_modified", [])
    
    # Gating checks
    is_valid = state.get("is_patch_valid", False)
    tests_passed = state.get("tests_passed", False)
    rescan_passed = state.get("rescan_passed", False)
    
    # Check if we should fallback to Mock PR
    if not token or github_mode != "LIVE" or not repo_url or "github.com" not in repo_url or not is_valid or not tests_passed or not rescan_passed or not files_modified:
        state["pr_url"] = f"https://github.com/mock-org/mock-repo/pull/{uuid.uuid4().hex[:6]}"
        state["pr_mode"] = "mock"
        reason = "LIVE mode conditions not met (requires LIVE mode, valid token, and passing validation/tests/rescan)."
        state["trace_logs"].append({
            "agent": "GitHub Action Agent", 
            "log": f"[MOCK] Created PR. Reason: {reason}"
        })
        return state
        
    try:
        # Parse owner/repo from URL
        repo_name = repo_url.rstrip("/").split("github.com/")[-1]
        
        g = Github(token)
        repo = g.get_repo(repo_name)
        
        # 1. Get default branch SHA
        default_branch = repo.default_branch
        ref = repo.get_git_ref(f"heads/{default_branch}")
        
        # 2. Create new branch
        short_id = uuid.uuid4().hex[:6]
        finding_rule = "security-fix"
        if state.get("scanner_findings") and len(state["scanner_findings"]) > 0:
            finding_rule = state["scanner_findings"][0].get("rule", "security-fix").split(".")[-1]
            
        # Sanitize rule name for branch
        finding_rule = re.sub(r'[^a-zA-Z0-9-]', '-', finding_rule).strip('-').lower()
        if not finding_rule:
            finding_rule = "security-fix"
            
        new_branch_name = f"buginsight/{finding_rule}-{short_id}"
        repo.create_git_ref(ref=f"refs/heads/{new_branch_name}", sha=ref.object.sha)
        
        # 3. Apply files
        for fm in files_modified:
            file_path = fm.get("file")
            content = fm.get("content")
            
            if not file_path or not content:
                continue
                
            # Normalize path for GitHub API (replace Windows backslashes)
            file_path = file_path.replace("\\", "/")
                
            # We now rely on ValidationAgent's Functional Preservation checks.
                
            # Get current file SHA
            try:
                contents = repo.get_contents(file_path, ref=default_branch)
                file_sha = contents.sha
                # Update file
                repo.update_file(
                    path=file_path, 
                    message=f"fix: autogenerated fix for {finding_rule}", 
                    content=content, 
                    sha=file_sha, 
                    branch=new_branch_name
                )
            except Exception as e:
                # If file doesn't exist or other error, create it instead (though it should exist)
                raise Exception(f"Failed to update file {file_path}: {str(e)}")
                
        # 4. Open PR
        finding = state.get("scanner_findings", [{}])[0]
        rule = finding.get("rule", "Unknown Rule")
        severity = finding.get("severity", "Unknown Severity")
        
        title = f"Fix: {rule} in {files_modified[0].get('file', 'codebase')}"
        
        # Format the Proof Report
        body = f"""# BugInsight Security Remediation

## Scanner Findings
Rule: `{rule}`
Severity: **{severity.upper()}**

## Root Cause
{state.get('root_cause', '')}

## Validation
Score: **{state.get('validation_score', 0)}/100**
Approved: **YES**

## Test Execution
Tests Passed: **YES**
Duration: {state.get('test_results', {}).get('duration', 0)}s

## Auto Rescan
Remaining Findings: **0**

## Fix Summary
{state.get('fix_summary', '')}

---
*Generated autonomously by [BugInsight Swarm](https://github.com/BIGREASONS/BugInsight-Swarm)*
"""
        
        pr = repo.create_pull(title=title, body=body, head=new_branch_name, base=default_branch)
        state["pr_url"] = pr.html_url
        state["pr_mode"] = "live"
        
        state["trace_logs"].append({
            "agent": "GitHub Action Agent", 
            "log": f"Successfully created LIVE Pull Request: {state['pr_url']}"
        })
    except Exception as e:
        # Fallback to mock mode on error
        mock_id = uuid.uuid4().hex[:6]
        state["pr_url"] = f"https://github.com/mock-org/mock-repo/pull/{mock_id}"
        state["pr_mode"] = "mock"
        state["trace_logs"].append({
            "agent": "GitHub Action Agent", 
            "log": f"[MOCK] LIVE mode failed ({type(e).__name__}: {str(e)}). Generated mock PR."
        })
        
    return state
